# Generated by Django 4.0.4 on 2022-07-13 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_book_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email',
            new_name='user',
        ),
    ]
