# Generated by Django 4.0.4 on 2022-07-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_email_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone_number',
            new_name='contacts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='other_contact_information',
        ),
    ]
