# Generated by Django 4.0.4 on 2022-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_phone_number_profile_contacts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='contacts',
            new_name='email',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
